In [1]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

import matplotlib.pyplot as plt

In [2]:
# CARGAR FEATURES
features = pd.read_csv(
    "../data/processed/features.csv"
)

In [3]:
# QUITAR TEXTO
features_numeric = features.drop(
    columns=["user_id", "categoria_favorita"]
)

In [4]:
# ESCALAR DATOS
scaler = StandardScaler()

scaled_data = scaler.fit_transform(
    features_numeric
)

In [5]:
# ENTRENAR KMEANS
kmeans = KMeans(
    n_clusters=4,
    random_state=42
)

clusters = kmeans.fit_predict(scaled_data)

In [6]:
# AGREGAR CLUSTER
features["cluster"] = clusters

In [7]:
# RESULTADOOOOOOS
features.head()

,user_id,gasto_total,gasto_promedio,num_transacciones,categoria_favorita,cashback_total,transacciones_internacionales,transacciones_atipicas,cluster
0,USR-00001,119570.59,2135.189107,56,servicios_digitales,122.33,2,0,3
1,USR-00002,212722.67,2874.630676,74,transferencia,147.08,1,0,3
2,USR-00003,190801.09,2415.203671,79,transferencia,165.43,4,0,3
3,USR-00004,580113.74,8789.602121,66,transferencia,0.00,2,0,0
4,USR-00005,190277.30,2045.992473,93,transferencia,162.99,1,0,3

In [8]:
# CONTAR USUARIOS POR CLUSTER
features["cluster"].value_counts()

cluster
3    5222
1    4602
0    4570
2     631
Name: count, dtype: int64

In [9]:
features.groupby("cluster").mean(numeric_only=True)

,gasto_total,gasto_promedio,num_transacciones,cashback_total,transacciones_internacionales,transacciones_atipicas
cluster,,,,,,
0,627574.987923,10166.133799,63.805689,421.158691,3.191466,0.058643
1,124484.151686,4384.118695,28.249674,28.804591,0.971100,0.435463
2,361643.763265,5956.033204,62.144216,190.566894,3.001585,62.144216
3,235768.631963,3728.247156,65.377825,94.381622,3.648985,0.000000

In [10]:
features.head()

,user_id,gasto_total,gasto_promedio,num_transacciones,categoria_favorita,cashback_total,transacciones_internacionales,transacciones_atipicas,cluster
0,USR-00001,119570.59,2135.189107,56,servicios_digitales,122.33,2,0,3
1,USR-00002,212722.67,2874.630676,74,transferencia,147.08,1,0,3
2,USR-00003,190801.09,2415.203671,79,transferencia,165.43,4,0,3
3,USR-00004,580113.74,8789.602121,66,transferencia,0.00,2,0,0
4,USR-00005,190277.30,2045.992473,93,transferencia,162.99,1,0,3

In [11]:
features.to_csv(
    "../data/processed/features.csv",
    index=False
)